# Generated by Django 5.1.1 on 2024-09-18 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('profesionales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('dia', models.DateField(help_text='Ingrese un dia para el turno.', null=True)),
                ('horario', models.CharField(choices=[('1', '07:00 a 08:00'), ('2', '08:00 a 09:00'), ('3', '09:00 a 10:00'), ('4', '10:00 a 11:00'), ('5', '11:00 a 12:00')], max_length=10, null=True)),
                ('motivo', models.TextField(max_length=500)),
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='clientes.cliente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='profesionales.profesional')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('dia', 'horario'), name='unique_dia_horario')],
            },
        ),
    ]
