# Generated by Django 5.1 on 2024-10-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_alter_turno_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='horario',
            field=models.CharField(choices=[('1', '07:00 a 07:30'), ('2', '07:30 a 08:00'), ('3', '08:00 a 08:30'), ('4', '08:30 a 09:00'), ('5', '09:00 a 09:30'), ('6', '09:30 a 10:00'), ('7', '10:00 a 10:30'), ('8', '10:30 a 11:00'), ('9', '11:00 a 11:30')], max_length=10, null=True),
        ),
    ]
