# Generated by Django 5.1.1 on 2024-10-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_alter_turno_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='horario',
            field=models.CharField(choices=[('07:00 a 07:30', '07:00 a 07:30'), ('07:30 a 08:00', '07:30 a 08:00'), ('08:00 a 08:30', '08:00 a 08:30'), ('08:30 a 09:00', '08:30 a 09:00'), ('09:00 a 09:30', '09:00 a 09:30'), ('09:30 a 10:00', '09:30 a 10:00'), ('10:00 a 10:30', '10:00 a 10:30'), ('10:30 a 11:00', '10:30 a 11:00'), ('11:00 a 11:30', '11:00 a 11:30')], max_length=50, null=True),
        ),
    ]
