# Generated by Django 5.1.1 on 2024-10-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_cliente_usuario'),
        ('profesionales', '0013_profesional_usuario'),
        ('turnos', '0005_alter_turno_horario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
        migrations.RemoveConstraint(
            model_name='turno',
            name='unique_dia_horario',
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(fields=('dia', 'horario', 'profesional'), name='unique_turno_profesional'),
        ),
    ]
