# Generated by Django 5.1.1 on 2024-10-15 17:47

from datetime import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0006_alter_turno_options_remove_turno_unique_dia_horario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='horario',
            field=models.DateTimeField(default=None, null=True),
            preserve_default=False,
        ),
    ]
