# Generated by Django 5.1.1 on 2024-10-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0009_turno_estado_alter_turno_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('Pendiente de aprobación', 'Pendiente de aprobación'), ('Aprobado', 'Aprobado'), ('Cancelado', 'Cancelado'), ('Concluido', 'Concluido')], default='Pendiente de aprobación', max_length=25),
        ),
    ]
