# Generated by Django 5.1.1 on 2024-10-21 22:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0010_alter_turno_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
