# Generated by Django 5.1.1 on 2024-10-22 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0011_turno_fecha_creacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
    ]
