# Generated by Django 5.1.1 on 2024-10-22 17:19

import django.db.models.deletion
import turnos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_rename_direccion_cliente_domicilio'),
        ('turnos', '0012_alter_turno_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[turnos.validators.validar_dni]),
        ),
        migrations.AddField(
            model_name='turno',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='telefono',
            field=models.CharField(max_length=10, null=True, validators=[turnos.validators.validar_telefono]),
        ),
        migrations.AlterField(
            model_name='turno',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='clientes.cliente'),
        ),
    ]
