# Generated by Django 5.1.1 on 2024-10-27 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0013_turno_dni_turno_nombre_completo_turno_telefono_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='nombre_completo',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='telefono',
        ),
    ]
