# Generated by Django 5.1.1 on 2024-10-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0014_remove_turno_dni_remove_turno_nombre_completo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='solicitante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
