# Generated by Django 5.1.1 on 2024-10-27 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_remove_cliente_usuario'),
        ('profesionales', '0022_remove_profesional_usuario'),
        ('turnos', '0015_turno_solicitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='cliente',
            field=models.ForeignKey(blank=True, default='-', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='motivo',
            field=models.TextField(blank=True, default='-', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='profesional',
            field=models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='profesionales.profesional'),
        ),
    ]
