# Generated by Django 5.1.1 on 2024-11-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0016_alter_turno_cliente_alter_turno_motivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('completado', models.BooleanField(default=False)),
            ],
        ),
    ]
