# Generated by Django 5.1.1 on 2024-11-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0018_delete_tarea_alter_turno_options_alter_turno_dia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='horario',
            field=models.CharField(choices=[('08:00 a 08:30', '08:00 a 08:30'), ('08:30 a 09:00', '08:30 a 09:00'), ('09:00 a 09:30', '09:00 a 09:30'), ('09:30 a 10:00', '09:30 a 10:00'), ('10:00 a 10:30', '10:00 a 10:30'), ('10:30 a 11:00', '10:30 a 11:00'), ('11:00 a 11:30', '11:00 a 11:30'), ('11:30 a 12:00', '11:30 a 12:00'), ('17:00 a 17:30', '17:00 a 17:30'), ('17:30 a 18:00', '17:30 a 18:00'), ('18:00 a 18:30', '18:00 a 18:30'), ('18:30 a 19:00', '18:30 a 19:00'), ('19:00 a 19:30', '19:00 a 19:30'), ('19:30 a 20:00', '19:30 a 20:00'), ('20:00 a 20:30', '20:00 a 20:30'), ('20:30 a 21:00', '20:30 a 21:00')], max_length=50),
        ),
    ]
