# Generated by Django 5.1.1 on 2024-09-08 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_alter_contacto_email'),
        ('profesionales', '0003_alter_contacto_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_profesional', models.BooleanField(default=False)),
                ('cliente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
                ('profesional', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profesionales.profesional')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
