# Generated by Django 5.1.1 on 2024-10-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_managers_remove_usuario_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('abogado', 'Abogado'), ('cliente', 'Cliente')], max_length=10),
        ),
    ]
