# Generated by Django 5.1.1 on 2024-10-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Abogado', 'Abogado'), ('Cliente', 'Cliente')], max_length=15),
        ),
    ]
