# Generated by Django 5.1.1 on 2024-10-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Abogado', 'Abogado'), ('Cliente', 'Cliente')], max_length=15),
        ),
    ]
