# Generated by Django 5.1.1 on 2024-11-16 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0023_secretaria'),
        ('usuarios', '0009_usuario_cliente_usuario_profesional'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='secretaria',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profesionales.secretaria'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Abogado', 'Abogado'), ('Cliente', 'Cliente'), ('Secretaria', 'Secretaria')], max_length=15),
        ),
    ]
