# Generated by Django 5.1.1 on 2024-11-18 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_usuario_secretaria_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['fecha_ingreso']},
        ),
    ]
