# Generated by Django 5.1.1 on 2024-09-08 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_cliente_remove_contacto_profesional_contacto_cliente_and_more'),
        ('profesionales', '0002_profesional_remove_contacto_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('numero_expediente', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('tipo_expediente', models.CharField(choices=[('Alimentos', 'Alimentos'), ('Division de bienes', 'Division de bienes')], max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Giro', 'Giro'), ('Paralizado', 'Paralizado')], max_length=50)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('asunto', models.TextField(max_length=250)),
                ('motivo', models.TextField(max_length=250)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.cliente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='profesionales.profesional')),
            ],
        ),
    ]
