# Generated by Django 5.1.1 on 2024-09-08 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_contacto_email'),
        ('expedientes', '0001_initial'),
        ('profesionales', '0003_alter_contacto_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expedientes', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expedientes', to='profesionales.profesional'),
        ),
    ]
