# Generated by Django 5.1.1 on 2024-10-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0003_alter_expediente_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='apoderado',
            field=models.CharField(blank=True, default='-', max_length=250, null=True),
        ),
    ]
