# Generated by Django 5.1.1 on 2024-10-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0004_alter_expediente_apoderado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientos',
            name='id',
        ),
        migrations.AddField(
            model_name='movimientos',
            name='id_mov',
            field=models.AutoField(default='0', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
