# Generated by Django 5.1.1 on 2024-10-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0005_remove_movimientos_id_movimientos_id_mov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='estado',
            field=models.CharField(blank=True, choices=[('Activo', 'Activo'), ('Giro', 'Giro'), ('Paralizado', 'Paralizado')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
