# Generated by Django 5.1.1 on 2024-10-14 23:10

import expedientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0006_alter_movimientos_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='archivos',
            field=models.FileField(blank=True, null=True, upload_to='documentos/', validators=[expedientes.models.validar_tipo_archivo]),
        ),
    ]
