# Generated by Django 5.1.1 on 2024-10-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0007_alter_movimientos_archivos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientos',
            old_name='observaciones',
            new_name='detalle',
        ),
        migrations.RemoveField(
            model_name='movimientos',
            name='estado',
        ),
        migrations.AddField(
            model_name='movimientos',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientos',
            name='sit_Actual',
            field=models.CharField(blank=True, choices=[('En letra', 'En letra'), ('A despacho', 'A despacho'), ('Giro', 'Giro'), ('En fiscalía', 'En fiscalía'), ('Prearchivado', 'Prearchivado'), ('Archivado', 'Archivado')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movimientos',
            name='tipo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
