# Generated by Django 5.1.1 on 2024-10-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0009_alter_movimientos_sit_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='detalle',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
