# Generated by Django 5.1.1 on 2024-10-17 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0010_alter_movimientos_detalle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientos',
            old_name='sit_Actual',
            new_name='sit_actual',
        ),
    ]
