# Generated by Django 5.1.1 on 2024-10-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0011_rename_sit_actual_movimientos_sit_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='detalle',
            field=models.TextField(blank=True, default='-', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='fecha',
            field=models.DateField(blank=True, default='-', null=True),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='sit_actual',
            field=models.CharField(blank=True, choices=[('En letra', 'En letra'), ('A despacho', 'A despacho'), ('Giro', 'Giro'), ('En fiscalía', 'En fiscalía'), ('Prearchivado', 'Prearchivado'), ('Archivado', 'Archivado')], default='-', max_length=50, null=True, verbose_name='Situación actual'),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='tipo',
            field=models.CharField(blank=True, default='-', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='ubicacion',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
    ]
