# Generated by Django 5.1.1 on 2024-10-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0012_alter_movimientos_detalle_alter_movimientos_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='tipo_expediente',
        ),
        migrations.AddField(
            model_name='expediente',
            name='caratula',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='dependencia',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='jurisdiccion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Jurisdicción'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='asunto',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
