# Generated by Django 5.1.1 on 2024-10-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0014_expediente_estado_alter_expediente_numero_expediente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='apoderado',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='detalle',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='tipo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
