# Generated by Django 5.1.1 on 2024-10-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0015_alter_expediente_apoderado_alter_movimientos_detalle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='sit_actual',
            field=models.CharField(blank=True, choices=[('En letra', 'En letra'), ('A despacho', 'A despacho'), ('Giro', 'Giro'), ('En fiscalía', 'En fiscalía'), ('Prearchivado', 'Prearchivado'), ('Archivado', 'Archivado')], max_length=50, null=True, verbose_name='Situación actual'),
        ),
    ]
