# Generated by Django 5.1.1 on 2024-10-21 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0016_alter_movimientos_sit_actual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientos',
            old_name='archivos',
            new_name='documentos',
        ),
    ]
