# Generated by Django 5.1.1 on 2024-10-21 19:57

import django.db.models.deletion
import expedientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0017_rename_archivos_movimientos_documentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientos',
            name='documentos',
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentos', models.FileField(upload_to='documentos/', validators=[expedientes.models.validar_tipo_archivo])),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='expedientes.movimientos')),
            ],
        ),
    ]
