# Generated by Django 5.1.1 on 2024-11-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0018_remove_movimientos_documentos_documentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='tipo_expediente',
            field=models.CharField(blank=True, choices=[('DOC', 'Documento'), ('INV', 'Investigación'), ('CON', 'Contrato'), ('TRA', 'Tratado')], max_length=3, null=True, verbose_name='Tipo de expediente'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='asunto',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
