# Generated by Django 5.1.1 on 2024-11-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0019_expediente_tipo_expediente_alter_expediente_asunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='sit_actual',
            field=models.CharField(choices=[('En letra', 'En letra'), ('A despacho', 'A despacho'), ('Giro', 'Giro'), ('En fiscalía', 'En fiscalía'), ('Prearchivado', 'Prearchivado'), ('Archivado', 'Archivado')], max_length=50, null=True, verbose_name='Situación actual'),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='tipo',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='ubicacion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
