# Generated by Django 5.1.1 on 2024-09-18 19:51

import clientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('dni', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True, verbose_name='Dni')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimmiento')),
                ('nacionalidad', models.CharField(max_length=50, verbose_name='Nacionalidad')),
                ('ocupacion', models.CharField(max_length=50, verbose_name='Ocupación')),
                ('lugar_laboral', models.CharField(max_length=100, verbose_name='Lugar laboral')),
                ('años_aportes', models.IntegerField(default=None, verbose_name='Años de aportes')),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('cod_postal', models.CharField(blank=True, max_length=4, null=True)),
                ('telefono', models.CharField(max_length=10, null=True, validators=[clientes.models.validar_telefono])),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
