# Generated by Django 5.1.1 on 2024-09-08 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('tipo_matricula', models.CharField(choices=[('DNI', 'DNI'), ('CUIL', 'CUIL')], default='DNI', max_length=200)),
                ('num_matricula', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=50)),
                ('ocupacion', models.CharField(max_length=50)),
                ('lugar_laboral', models.CharField(max_length=100)),
                ('años_aportes', models.IntegerField(default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='profesional',
        ),
        migrations.AddField(
            model_name='contacto',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.cliente'),
        ),
        migrations.DeleteModel(
            name='Profesional',
        ),
    ]
