# Generated by Django 5.1.1 on 2024-09-18 20:22

import clientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='años_aportes',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Años de aportes'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, validators=[clientes.models.validar_dni], verbose_name='Dni'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='lugar_laboral',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar laboral'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ocupación'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(help_text='ej: 3794541234', max_length=10, null=True, validators=[clientes.models.validar_telefono]),
        ),
    ]
