# Generated by Django 5.1 on 2024-09-20 19:25

import clientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_años_aportes_alter_cliente_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=10, null=True, validators=[clientes.models.validar_telefono]),
        ),
    ]
