# Generated by Django 5.1 on 2024-09-20 23:25

import clientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cod_postal',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[clientes.models.validar_codPostal], verbose_name='Codigo postal'),
        ),
    ]
