# Generated by Django 5.1.1 on 2024-10-02 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_cliente_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
    ]
