# Generated by Django 5.1.1 on 2024-10-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_cliente_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_ingreso',
            field=models.DateField(default='2024-01-01', verbose_name='Fecha de ingreso'),
            preserve_default=False,
        ),
    ]
