# Generated by Django 5.1.1 on 2024-10-20 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_cliente_fecha_ingreso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='direccion',
            new_name='domicilio',
        ),
    ]
