# Generated by Django 5.1.1 on 2024-09-08 00:29

import django.db.models.deletion
import profesionales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('tipo_matricula', models.CharField(choices=[('DNI', 'DNI'), ('CUIL', 'CUIL')], default='DNI', max_length=200)),
                ('num_matricula', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=50)),
                ('ocupacion', models.CharField(max_length=50)),
                ('lugar_laboral', models.CharField(max_length=100)),
                ('años_aportes', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('cod_postal', models.CharField(blank=True, max_length=4, null=True)),
                ('telefono', models.CharField(max_length=10, null=True, validators=[profesionales.models.validar_telefono])),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='profesionales.cliente')),
            ],
        ),
    ]
