# Generated by Django 5.1.1 on 2024-09-18 19:51

import django.db.models.deletion
import profesionales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('dni', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True, verbose_name='DNI')),
                ('idMatriculaProf', models.IntegerField(unique=True, verbose_name='Numero de matricula del profesional')),
                ('especialidad', models.CharField(choices=[('Familia', 'Familia'), ('Laboral', 'Laboral')], max_length=200)),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('fecha_egreso', models.DateField(blank=True, null=True, verbose_name='Fecha de egreso')),
                ('motivo_egreso', models.TextField(blank=True, max_length=250, null=True, verbose_name='Motivo de egreso')),
            ],
            options={
                'verbose_name_plural': 'Profesionales',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('cod_postal', models.CharField(blank=True, max_length=4, null=True)),
                ('telefono', models.CharField(max_length=10, null=True, validators=[profesionales.models.validar_telefono])),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('profesional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='profesionales.profesional')),
            ],
        ),
    ]
