# Generated by Django 5.1.1 on 2024-09-18 20:17

import profesionales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='cod_postal',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='profesional',
            name='direccion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profesional',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profesional',
            name='telefono',
            field=models.CharField(max_length=10, null=True, validators=[profesionales.models.validar_telefono]),
        ),
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
