# Generated by Django 5.1.1 on 2024-09-08 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('tipo_matricula', models.CharField(choices=[('DNI', 'DNI'), ('CUIL', 'CUIL')], default='DNI', max_length=200)),
                ('num_matricula', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('idMatriculaProf', models.IntegerField(unique=True)),
                ('especialidad', models.CharField(choices=[('FLIA', 'Familia'), ('LAB', 'Laboral')], max_length=200)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_egreso', models.DateField(blank=True, null=True)),
                ('motivo_egreso', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='cliente',
        ),
        migrations.AddField(
            model_name='contacto',
            name='profesional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='profesionales.profesional'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
