# Generated by Django 5.1.1 on 2024-09-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0002_profesional_remove_contacto_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
    ]
