# Generated by Django 5.1 on 2024-10-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0004_alter_profesional_dni_alter_profesional_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='foto',
            field=models.ImageField(blank=True, default='images/perfil_default.webp', null=True, upload_to='images/'),
        ),
    ]
