# Generated by Django 5.1 on 2024-10-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0005_profesional_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='foto',
            field=models.ImageField(blank=True, default='static/images/perfil_default.webp', null=True, upload_to='static/images/'),
        ),
    ]
