# Generated by Django 5.1 on 2024-10-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0008_alter_profesional_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='cod_postal',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Codigo Postal'),
        ),
    ]
