# Generated by Django 5.1 on 2024-10-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0009_alter_profesional_cod_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('baja', 'Baja')], default='Activo', max_length=10),
        ),
    ]
