# Generated by Django 5.1 on 2024-10-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0010_profesional_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Baja', 'Baja')], default='Activo', max_length=10),
        ),
    ]
