# Generated by Django 5.1 on 2024-10-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0011_alter_profesional_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Foto'),
        ),
    ]
