# Generated by Django 5.1.1 on 2024-10-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0013_profesional_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10),
        ),
    ]
