# Generated by Django 5.1.1 on 2024-10-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0016_alter_profesional_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('Derecho de familia', 'Derecho de familia'), ('Derecho penal', 'Derecho penal'), ('Derecho laboral', 'Derecho laboral'), ('Derecho de daños', 'Derecho de daños'), ('Derecho sucesorio', 'Derecho sucesorio'), ('Derecho de daños', 'Derecho de daños'), ('Derecho de daños', 'Derecho de daños'), ('Derecho deportivo', 'Derecho deportivo')], max_length=200, null=True),
        ),
    ]
