# Generated by Django 5.1.1 on 2024-10-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0017_alter_profesional_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='idMatriculaProf',
            field=models.IntegerField(unique=True, verbose_name='Nº matricula del profesional'),
        ),
    ]
