# Generated by Django 5.1.1 on 2024-10-20 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0020_alter_profesional_idmatriculaprof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesional',
            old_name='direccion',
            new_name='domicilio',
        ),
    ]
