# Generated by Django 5.1.1 on 2024-10-23 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0021_rename_direccion_profesional_domicilio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional',
            name='usuario',
        ),
    ]
