# Generated by Django 5.1.1 on 2024-11-16 22:24

import django.db.models.deletion
import profesionales.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0022_remove_profesional_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('fecha_egreso', models.DateField(blank=True, null=True, verbose_name='Fecha de egreso')),
                ('motivo_egreso', models.TextField(blank=True, max_length=250, null=True, verbose_name='Motivo de egreso')),
                ('domicilio', models.CharField(blank=True, max_length=250, null=True)),
                ('cod_postal', models.CharField(blank=True, max_length=4, null=True, verbose_name='Codigo Postal')),
                ('telefono', models.CharField(max_length=10, null=True, validators=[profesionales.validators.validar_telefono])),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretarias', to='profesionales.profesional')),
            ],
        ),
    ]
