# Generated by Django 5.1.1 on 2024-11-16 23:16

import profesionales.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0023_secretaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretaria',
            name='id',
        ),
        migrations.AddField(
            model_name='secretaria',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='dni',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, validators=[profesionales.validators.validar_dni], verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='telefono',
            field=models.CharField(default='0000000000', max_length=10, validators=[profesionales.validators.validar_telefono]),
            preserve_default=False,
        ),
    ]
