# Generated by Django 5.1.1 on 2024-11-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0024_remove_secretaria_id_secretaria_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretaria',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Foto'),
        ),
    ]
